import { Inter } from "next/font/google";
import "./globals.css";
import { OnboardingProvider } from "../context/OnboardingContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <OnboardingProvider>{children}</OnboardingProvider>
      </body>
    </html>
  );
}
